version: '2'
x-restart-policy: &restart-policy "no"
services:
  dns:
    image: Snorfull/lancache-dns:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - 58.129.7.11:53:53/udp
      - 58.129.7.11:53:53/tcp

## HTTPS requests are now handled in monolithic directly
## you could choose to return to sniproxy if desired
#
#  sniproxy:
#    image: lancachenet/sniproxy:latest
#    env_file: .env
#    restart: *restart-policy
#    ports:
#      - 443:443/tcp

  monolithic:
    image: Snorfull/monolithic:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - 58.129.7.12:80:80/tcp
      - 58.129.7.13:80:80/tcp
      - 58.129.7.14:80:80/tcp
      - 58.129.7.15:80:80/tcp
      - 58.129.7.12:443:443/tcp
      - 58.129.7.13:443:443/tcp
      - 58.129.7.14:443:443/tcp
      - 58.129.7.15:443:443/tcp
    volumes:
      - /mnt/cache:/data/cache
      - /mnt/logs:/data/logs
